mis/urls.py
from django.urls import path
from mis import views

urlpatterns = [

	path('',views.index,name='index'),
	path('book/<int:pk>',views.BookDetailView.as_view(),name='book-detail'),
	path('books',views.BookListView.as_view(),name='books'),
	path('author/<int:pk>',views.AuthorDetailView.as_view(),name='author-detail'),
	path('authors',views.AuthorListView.as_view(),name='authors'),

]

school/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mis.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

mis/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
import uuid

# Create your models here.
class Klass(models.Model):
	Klass = models.CharField(max_length=200)

	def __str__(self):
		return self.Klass

class Teacher(models.Model):
	Name = models.CharField(max_length=200)

	def __str__(self):

		return self.Name

class Country(models.Model):
	Country_Name = models.CharField(max_length=200)

	def __str__(self):

		return self.Country_Name

class District(models.Model):

	District_Name = models.CharField(max_length=200)

	def __str__(self):

		return self.District_Name

class Student(models.Model):

	First_Name = models.CharField(max_length=200)
	Last_Name = models.CharField(max_length=200)
	DOB = models.DateField(blank=True, null=True)
	Registration_Date = models.DateField()
	Guadian_Contact = models.CharField(max_length=200)
	Klass = models.ForeignKey('Klass',on_delete=models.CASCADE)
	District = models.ForeignKey('District',on_delete=models.CASCADE)
	Class_Teacher = models.ForeignKey('Teacher',on_delete=models.CASCADE)
	Citizenship = models.ForeignKey('Country',on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.First_Name},{self.Last_Name}'



class Genre(models.Model):

	name = models.CharField(max_length=200,help_text='Enter a book genre (e.g. Science Fiction)')

	def __str__(self):
		return self.name

class Book(models.Model):

	title = models.CharField(max_length=200)
	author = models.ForeignKey('Author',on_delete=models.CASCADE)
	summary = models.TextField(max_length=1000)
	isbn =  models.CharField('ISBN',max_length=13,help_text='Enter 13 character')
	genre = models.ManyToManyField(Genre,help_text='select genre for this book')

	def __str__(self):
		return self.title

	def get_absolute_url(self):

		return reverse('book-detail',args=[str(self.id)])

class BookIstance(models.Model):
	id = models.UUIDField(primary_key=True,default=uuid.uuid4,help_text='Unique ID for this particular book across whole library')
	book = models.ForeignKey('Book',on_delete=models.CASCADE)
	imprint = models.CharField(max_length=200)
	due_back = models.DateField(null=True,blank=True)
	LOAN_STATUS = (

		('m','Maintenance'),
		('o','On loan'),
		('a','Available'),
		('r','Reserved'),

	)

	status = models.CharField(
		max_length=1,
		choices=LOAN_STATUS,
		blank=True,
		default='m',
		help_text='Book availability',

	)

	def __str__(self):
		return f'{self.id},({self.book.title})'


class Author(models.Model):
	First_Name = models.CharField(max_length=100)
	Last_Name = models.CharField(max_length=100)
	DOB = models.DateField(null=True,blank=True)
	DOD = models.DateField('Died',null=True,blank=True)

	def __str__(self):
		return f'{self.First_Name},{self.Last_Name}'

	def get_absolute_url(self):

		return reverse('author-detail',args=[str(self.id)])

mis/views.py
from django.shortcuts import render
from .models import Student,Book,Author,BookIstance
from django.views import generic

# Create your views here.

def index(request):

	total_no_of_students = Student.objects.all().count()
	total_no_of_books = Book.objects.all().count()
	#number of authors
	total_no_of_authors = Author.objects.all().count()
	total_no_of_Instances = BookIstance.objects.all().count()
	total_no_of_Instances_available = BookIstance.objects.filter(status__exact='a').count()
	#vist counts tracking using sessions as below

	vist_num = request.session.get('vist_num',0)
	request.session['vist_num'] = vist_num + 1

	context = {

		'total_no_of_students':total_no_of_students,
		'total_no_of_books':total_no_of_books,
		'total_no_of_authors':total_no_of_authors,
		'total_no_of_Instances':total_no_of_Instances,
		'total_no_of_Instances_available':total_no_of_Instances_available,
		'vist_num':vist_num,
	}
	return render(request,'index.html',context=context)

class BookDetailView(generic.DetailView):

	model = Book


class BookListView(generic.ListView):
	model = Book


class AuthorDetailView(generic.DetailView):
	model=Author

class AuthorListView(generic.ListView):
	model=Author

mis/templates/base_temp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>LIB Admin - Dashboard</title>

      {% load static %}
    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

      <a class="navbar-brand mr-1" href="index.html">School LIB</a>

      <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
      </button>

      <!-- Navbar Search -->
      <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-primary" type="button">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
      </form>

      <!-- Navbar -->
      <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown no-arrow mx-1">
          <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bell fa-fw"></i>
            <span class="badge badge-danger">9+</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown no-arrow mx-1">
          <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-envelope fa-fw"></i>
            <span class="badge badge-danger">7</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle fa-fw"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#">Settings</a>
            <a class="dropdown-item" href="#">Activity Log</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
          </div>
        </li>
      </ul>

    </nav>

    <div id="wrapper">

      <!-- Sidebar -->
      <ul class="sidebar navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="pagesDropdown">
            <h6 class="dropdown-header">Login Screens:</h6>
            <a class="dropdown-item" href="login.html">Login</a>
            <a class="dropdown-item" href="register.html">Register</a>
            <a class="dropdown-item" href="forgot-password.html">Forgot Password</a>
            <div class="dropdown-divider"></div>
            <h6 class="dropdown-header">Other Pages:</h6>
            <a class="dropdown-item" href="404.html">404 Page</a>
            <a class="dropdown-item" href="blank.html">Blank Page</a>
          </div>
        </li>

                <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">
            <i class="fas fa-fw fa-home"></i>
            <span>Home</span></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'books' %}">
            <i class="fas fa-fw fa-book"></i>
            <span>All Books</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authors' %}">
            <i class="fas fa-fw fa-user"></i>
            <span>All Authors</span></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="fas fa-fw fa-user"></i>
            <span>All Students</span></a>
        </li>

      </ul>

      <div id="content-wrapper">

        <div class="container-fluid">

          <!-- Breadcrumbs-->
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="#">Book Details</a>
            </li>
            <li class="breadcrumb-item active">Overview</li>
          </ol>


  

          <!-- Area Chart Example-->
          <div class="card mb-3">
            <div class="card-header">
              <i class="fas fa-chart-area"></i>
              School Lib Introduction</div>
            <div class="card-body">
              {% block content %}
              {% endblock %}   
            </div>
          </div>
          </div>

        </div>
        <!-- /.container-fluid -->

        <!-- Sticky Footer -->
        <footer class="sticky-footer">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>For support contact +256 754523742</span>
            </div>
          </div>
        </footer>

      </div>
      <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="login.html">Logout</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Page level plugin JavaScript-->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>

    <!-- Demo scripts for this page-->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>

  </body>

</html>

mis/templates/book_list.htm
{% extends "base_temp.html" %}

mis/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>LIB Admin - Dashboard</title>

      {% load static %}
    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

      <a class="navbar-brand mr-1" href="index.html">School LIB</a>

      <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
      </button>

      <!-- Navbar Search -->
      <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-primary" type="button">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
      </form>

      <!-- Navbar -->
      <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown no-arrow mx-1">
          <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bell fa-fw"></i>
            <span class="badge badge-danger">9+</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown no-arrow mx-1">
          <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-envelope fa-fw"></i>
            <span class="badge badge-danger">7</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle fa-fw"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#">Settings</a>
            <a class="dropdown-item" href="#">Activity Log</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
          </div>
        </li>
      </ul>

    </nav>

    <div id="wrapper">

      <!-- Sidebar -->
      <ul class="sidebar navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="pagesDropdown">
            <h6 class="dropdown-header">Login Screens:</h6>
            <a class="dropdown-item" href="login.html">Login</a>
            <a class="dropdown-item" href="register.html">Register</a>
            <a class="dropdown-item" href="forgot-password.html">Forgot Password</a>
            <div class="dropdown-divider"></div>
            <h6 class="dropdown-header">Other Pages:</h6>
            <a class="dropdown-item" href="404.html">404 Page</a>
            <a class="dropdown-item" href="blank.html">Blank Page</a>
          </div>
        </li>
            <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">
            <i class="fas fa-fw fa-home"></i>
            <span>Home</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books' %}">
            <i class="fas fa-fw fa-book"></i>
            <span>All Books</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-user"></i>
            <span>All Authors</span></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#">
            <span><p>You have visted this page</p> {{vist_num}} times </span></a>
        </li>


      </ul>

      <div id="content-wrapper">

        <div class="container-fluid">

          <!-- Breadcrumbs-->
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="#">Dashboard</a>
            </li>
            <li class="breadcrumb-item active">Overview</li>
          </ol>

          <!-- Icon Cards-->
          <div class="row">
            <div class="col-xl-3 col-sm-6 mb-3">
              <div class="card text-white bg-primary o-hidden h-100">
                <div class="card-body">
                  <div class="card-body-icon">
                    <i class="fas fa-fw fa-comments"></i>
                  </div>
                  <div class="mr-5">Total Books::</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="#">
                  <span class="float-left"><strong>{{ total_no_of_books }} Books in Lib</span></strong>
                  <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                  </span>
                </a>
              </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
              <div class="card text-white bg-warning o-hidden h-100">
                <div class="card-body">
                  <div class="card-body-icon">
                    <i class="fas fa-fw fa-list"></i>
                  </div>
                  <div class="mr-5">Total Copies!</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="#">
                  <span class="float-left">{{ total_no_of_Instances }}</span>
                  <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                  </span>
                </a>
              </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
              <div class="card text-white bg-success o-hidden h-100">
                <div class="card-body">
                  <div class="card-body-icon">
                    <i class="fas fa-fw fa-shopping-cart"></i>
                  </div>
                  <div class="mr-5">Copies available</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="#">
                  <span class="float-left">{{ total_no_of_Instances_available }}</span>
                  <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                  </span>
                </a>
              </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
              <div class="card text-white bg-danger o-hidden h-100">
                <div class="card-body">
                  <div class="card-body-icon">
                    <i class="fas fa-fw fa-life-ring"></i>
                  </div>
                  <div class="mr-5">Authors</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="#">
                  <span class="float-left">{{ total_no_of_authors }}</span>
                  <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                  </span>
                </a>
              </div>
            </div>
          </div>

          <!-- Area Chart Example-->
          <div class="card mb-3">
            <div class="card-header">
              <i class="fas fa-chart-area"></i>
              School Lib Introduction</div>
            <div class="card-body">
            <table>
              <tr><td><strong>Welcome to School Lib .. Plis submit any of
              your queries if any . Note the following </strong></td></tr>
              <tr><td><li>This is a trial version.. any of your contributions are welcome</li></td></tr>
              <tr><td><li>I am planning to avail the code so that any one can contribute</li></td></tr>
              <tr><td><li>Find my contacts below for more info</li></td></tr>
              
            </table>     
            </div>
          </div>
          </div>

        </div>
        <!-- /.container-fluid -->

        <!-- Sticky Footer -->
        <footer class="sticky-footer">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>For support contact +256 754523742</span>
            </div>
          </div>
        </footer>

      </div>
      <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="login.html">Logout</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Page level plugin JavaScript-->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>

    <!-- Demo scripts for this page-->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>

  </body>

</html>

mis/templates/mis/author_detail.html
{% extends "base_temp.html" %}

{% block content %}

<h4> You are viewing author <a href="#">{{author.First_Name}} {{author.Last_Name}}</a> </h4>
<p>Date of Birth: <strong>{{author.DOB}}</strong></p>

	

{% endblock %}

mis/templates/mis/author_list.html
{% extends "base_temp.html" %}

	{% block content %}

	<h4> List of Authors </h4>

		{% if author_list %}
			{% for author in author_list %}

			<li><a href="{{ author.get_absolute_url }}">{{author.First_Name}}</a>{{author.Last_Name}} </li>

			{% endfor %}

			{% else %}

				<p>No Authors currently </p>

		{% endif %}


	{% endblock %}

mis/templates/mis/book_detail.html
{% extends "base_temp.html"%}
{% block content %}
	
	<h1>Title : {{ book.title }}</h1>
		<p><strong>Author : {{ book.author }}</strong></p>
		<p><strong>Summary : {{book.summary}}</strong></p>
		<p> <strong>ISBNN  : {{book.isbn}}</strong></p>

	<div style="margin-left: 20px; margin-top: 20px">
		<h4>Copies: </h4>

		  	 {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{copy.imprint}}</p>
      <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>

{% endblock %}

mis/templates/mis/book_list.html
{% extends "base_temp.html" %}

{% block content %}

<h1>List of available books </h1>

{% if book_list %}

<ul> {% for book in book_list %}</ul>

		<li>
			<a href="{{ book.get_absolute_url }}">{{book.title}}</a>({{book.author}})
		</li>
		{% endfor %}

		{% else %}

			<p>There are no books in the lib </p>

			{% endif %}

	{% endblock %}